CREATE SEQUENCE IF NOT EXISTS user_id_seq INCREMENT BY 1;

CREATE TABLE node
(
    id      BIGINT       NOT NULL,
    name    VARCHAR(255) NOT NULL,
    text    VARCHAR(255),
    user_id BIGINT       NOT NULL,
    CONSTRAINT node_pkey PRIMARY KEY (id, user_id)
);

CREATE TABLE "user"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    count_nodes BIGINT DEFAULT 0,
    password    VARCHAR(255)                            NOT NULL,
    username    VARCHAR(50)                             NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

ALTER TABLE node
    ADD CONSTRAINT FK7fi376i6naekbnkmnf3pmchyk FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE NO ACTION;