@home=localhost:8080
###
@id=1
GET {{home}}/{{id}}

###
@username=luck
GET {{home}}/get_users
Content-Type: application/json

{
  "username": "{{username}}"
}

###
POST {{home}}/create_user
Content-Type: application/json

{
  "username": "{{username}}"
}

###
DELETE {{home}}/delete_user
Content-Type: application/json

{
  "id": 6
}

###
GET {{home}}/1/5

###
POST {{home}}/add_node
Content-Type: application/json

{
  "user_id": 1,
  "text": "ololo999"
}

###
DELETE {{home}}/delete_node
Content-Type: application/json

{
  "user_id": 1,
  "id": 0
}

###
PATCH {{home}}/edit_node
Content-Type: application/json

{
  "user_id": 1,
  "id": 5,
  "text": "Работоспособность"
}