@home=localhost:8080
###
@id=1
GET {{home}}/{{id}}

###
@username=luck
GET {{home}}/get_users
Content-Type: application/json

{
  "username": "{{username}}"
}

###
POST {{home}}/create_user
Content-Type: application/json

{
  "username": "{{username}}"
}

###
DELETE {{home}}/delete_user
Content-Type: application/json

{
  "id": 6
}