@home=localhost:8080
###
@id=1
GET {{home}}/{{id}}

###
@username=L
GET {{home}}/get_users
Content-Type: application/json

{
  "username": "{{username}}"
}

###
POST {{home}}/create_user
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "123321"
}

###
DELETE {{home}}/delete_user
Content-Type: application/json

{
  "id": 2,
  "username": "luck",
  "password": "123321"
}

###
PATCH {{home}}/update_user
Content-Type: application/json

{
  "id": 1,
  "username": "L",
  "password": "PassWordForWord",
  "new_username": "",
  "new_password": "123321"
}

###
GET {{home}}/1/2
Content-Type: application/json

{
  "id": 1,
  "username": "L",
  "password": "123321"
}

###
POST {{home}}/add_node
Content-Type: application/json

{
  "user_id": 1,
  "username": "L",
  "password": "123321",
  "name": "testTest",
  "text": "dsfdsijfhdijsfhidsfdsfdsfdsf"
}

###
DELETE {{home}}/delete_node
Content-Type: application/json

{
  "id": 1,
  "user_id": 1,
  "username": "L",
  "password": "123321"
}

###
PATCH {{home}}/edit_node
Content-Type: application/json

{
  "id": 1,
  "user_id": 1,
  "username": "L",
  "password": "123321",
  "name": "Что требуется на работе?",
  "text": "Работоспособность"
}